-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sc_7seg_conv is
port (
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    i_value : IN STD_LOGIC_VECTOR (31 downto 0);
    o_value : OUT STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000" );
end;


architecture behav of sc_7seg_conv is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sc_7seg_conv,hls_ip_2015_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.680000,HLS_SYN_LAT=147,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=456,HLS_SYN_LUT=444}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal grp_sc_7seg_conv_do_gen_fu_52_i_value : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sc_7seg_conv_do_gen_fu_52_o_value : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sc_7seg_conv_do_gen_fu_52_o_value_ap_vld : STD_LOGIC;
    signal grp_sc_7seg_conv_do_gen_fu_52_iStart : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_27 : BOOLEAN;

    component sc_7seg_conv_do_gen IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        i_value : IN STD_LOGIC_VECTOR (31 downto 0);
        o_value : OUT STD_LOGIC_VECTOR (31 downto 0);
        o_value_ap_vld : OUT STD_LOGIC;
        iStart : IN STD_LOGIC );
    end component;



begin
    grp_sc_7seg_conv_do_gen_fu_52 : component sc_7seg_conv_do_gen
    port map (
        ap_clk => clk,
        ap_rst => reset,
        i_value => grp_sc_7seg_conv_do_gen_fu_52_i_value,
        o_value => grp_sc_7seg_conv_do_gen_fu_52_o_value,
        o_value_ap_vld => grp_sc_7seg_conv_do_gen_fu_52_o_value_ap_vld,
        iStart => grp_sc_7seg_conv_do_gen_fu_52_iStart);





    -- o_value assign process. --
    o_value_assign_proc : process(clk)
    begin
        if (clk'event and clk =  '1') then
            if (reset = '1') then
                o_value <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = grp_sc_7seg_conv_do_gen_fu_52_o_value_ap_vld)) then 
                    o_value <= grp_sc_7seg_conv_do_gen_fu_52_o_value;
                end if; 
            end if;
        end if;
    end process;

    ap_CS_fsm <= ap_const_lv2_0;

    -- ap_sig_bdd_27 assign process. --
    ap_sig_bdd_27_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_27 <= (ap_CS_fsm(1 downto 1) = ap_const_lv1_1);
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_27)
    begin
        if (ap_sig_bdd_27) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_sc_7seg_conv_do_gen_fu_52_iStart <= ap_const_logic_0;
    grp_sc_7seg_conv_do_gen_fu_52_i_value <= i_value;
end behav;
